name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - development



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          ref: development

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test -- --ci --coverage

      - name: Build
        run: webpack --config webpack.config.js

      - name: Verify Build Output
        run: ls -la ./build
      
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
